name: my_api
description: API package for MySuite applications
version: 0.0.1
homepage: https://github.com/RivMt

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http:

dev_dependencies:
  test:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0