/// Flutter icons CurrencySymbol
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CurrencySymbol
///      fonts:
///       - asset: fonts/CurrencySymbol.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CurrencySymbol {
  CurrencySymbol._();

  static const _kFontFam = 'CurrencySymbol';
  static const String? _kFontPkg = null;

  static const IconData fra = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gbp = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ils = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData inr = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData jpy = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData krw = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kzt = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mnt = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ngn = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData php = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rial = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rub = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sign = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thb = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lira = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twd = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uah = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bdt = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData usd = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brl = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData btc = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cny = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eur = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eth = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
